# 沒有拆分成 stage 跟 jobs (執行時間 Ran for 3 min 58 sec)
# services:
#   - docker
# env:
#   - DOCKER_COMPOSE_VERSION=1.23.2
# before_install:
#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin
#   - docker --version
# script:
#   - docker-compose build db
#   - docker-compose build static-analysis
#   - docker-compose build test-postgresql
#   - docker-compose run test-postgresql
#   - docker-compose run static-analysis

# 建立 1個stage 包含2個jobs (執行時間 Ran for 3 min 53 sec)
# services:
#   - docker
# env:
#   - DOCKER_COMPOSE_VERSION=1.23.2
# before_install:
#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin
#   - docker --version
# jobs:
#   include:
#     - stage: tests
#       name: "Unit Tests"
#       script:
#         - docker-compose build db
#         - docker-compose build test-postgresql
#         - docker-compose run test-postgresql
#     - stage: tests
#       name: "Static Analysis"
#       script:
#         - docker-compose build static-analysis
#         - docker-compose run static-analysis

# 包括 push 完成的 image 到 Docker Hub
services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: "YHfXK4RB8SFBGxO/tfuaN4NbAMsJ/9MqB5gJh3Je2uYc4oAIZWUwjdnyUXFzFxjv3jqo3qhSPKz/rsJCgeCHxbt9AAj/RWQH6Xh1cAsezyOGE0v9PxUIHVC3Bq/dw0SQgEId282JzqyVue5wi9OmpuRTSVDea58+7xOJ/MP23rwM6x/BqBid62TvGwhUzbsDVmlryh6Lics3638ak1SS7+UUmnTpgDaU6KGSmIzoyIFF8eadRyZAgcK+wUliPxQ2bMVgnTwh41uU/y8C1mt77q/PGSupyU/yUAR/ONaAamsPGiQLEQ6Vq6avgXeqHSYDMduI52PoUaLLTBqc771rvfbauaY3qRCzHEQDxSyYq4fnJ0Ez3cFbmLpb0Tpa5zedFSRlZ+7fxcqa8uqUNt2zvVlKzsCL2xDYTCe9WPeElJIDDJ6feZvq16xmRgmxQPsiSAEVKB2VBS83qMaz9VeLTrx376eejHxABeRe/1qWuBx6KFz8sA1gzBIqUi7lNwTQaqtc5gyEtVeuwEAjXxxV2ktnJ5A8kwz3HB2E4X/Vm/RMsVBHT7dM7joKVpdZCB+YBeq4ToKuWzMy1S723MFD6oxg03lXeGRN+Erh6wKEC4r3knePye1KhDg2PExNoI9BvJdj1a3prhSGkv6wUL9dReHtaRJgfYlmIToRfJcEsh0="
    - secure: "PDjOPRTeXuEewQyAY1WxWTmzruypwyrJAjMOwggyDo2YC2EZjwDlvxI+UFHryCR4HrF1qfRVYdtthJl5hMtD0Fqwu5+a5uY1xYvlran6/nPr68S1Dcq+l75/988EqDRnBL7kN2dM/i4wSwJ5UIyPWq5llGKfh7QXpGYMXa1iCmb1bagueOePJESj2io12DYVHq5OC4YjVqLbDMvCXG1rJj/Y4T7CP+luZTpjYaELNaHxaG2oEMs50bBU1hpepiA48IYPeLAf7K26Y4iElfBJCCk2TBCIU514EkHhGIyvFzwkEyA5vaq2wgC+MUaXNn6lmzpxR29Ukic3K45hVYFRbHfutqNkqMbdk5scEOpnsf/qGcjU3C4pOiuQjNNXmH6pdkL/OW03vshGn6k3R1RXvOwaVe1ejwhMvpwCXNvu1xZJ+4of+T0Xr/wP9VyxmosIwn6qmZPMPrMPAQb1/xsB9yfTKbPpYG442P7NhMfbTVYmeDAyxNp9aoEaLc3C5cGkBzkjK9D5obVrjHA7Ec/Xj9yqiRXa7Gjyx1YzEPgjwEVGWBlo7PaaD5t0TVF00K5TRw7N0oOznPPxh1j4hjv4/rhFxs4c0sg7/n7syhhkVD1I0OvNVjBEC0/G5k8btkhjhTOmRFovimgNSp5SkJ0nl0NIOjk8MyoNvc9cuoM7AF4="
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version
  - echo "Login into Docker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export GIT_SHA=`git rev-parse --short HEAD`
  - echo "Building commit $GIT_SHA"
jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
        - docker-compose build db
        - docker-compose build test-postgresql
        - docker-compose run test-postgresql
    - stage: tests
      name: "Static Analysis"
      script:
        - docker-compose build static-analysis
        - docker-compose run static-analysis
    - stage: push
      script:
        - docker-compose build server
        - docker tag thoughts_server:latest jaimebuelta/thoughts-backend:$GIT_SHA
        - docker push jaimebuelta/thoughts-backend:$GIT_SHA
        - docker tag thoughts_server:latest jaimebuelta/thoughts-backend:$TRAVIS_BRANCH
      deploy:
        - provider: script
          script: docker push jaimebuelta/thoughts-backend:$TRAVIS_BRANCH
          on:
            branch: master
        - provider: script
          script: docker push jaimebuelta/thoughts-backend:$TRAVIS_TAG
          on:
            tags: true
